function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	AddTextEntry('bmci', 'BMW M5')
	AddTextEntry('centuria', 'Bugatti Centuria')
	AddTextEntry('gcmlamboultimae', 'Lamborghini Aventador')
	AddTextEntry('ftecnica', 'Lamborghini Huracan')
	AddTextEntry('bmci', 'BMW M5')
	AddTextEntry('gtrh', 'GTRH')
	AddTextEntry('18performante', 'Lamborghini Performance')
	AddTextEntry('812mnsry', 'Ferrari Mansory')
	AddTextEntry('m4lb2', 'BMW M4')
	AddTextEntry('c8', 'Chevrolet C8')
	AddTextEntry('488mishasp', 'Ferrari 488')
	AddTextEntry('c8p1', 'Chevrolet Corvette')
	AddTextEntry('M4CC', 'M4 Compétition')
	AddTextEntry('r820', 'Audi R8')
	AddTextEntry('rs6abt20', 'RS6 ABT')
	AddTextEntry('charger21', 'Dodge Charger')
	AddTextEntry('amrevu23mg', 'Lamborghini Revelto')
	AddTextEntry('furai', 'Mazda Furai')
	AddTextEntry('sinacp', 'Lamborghini SINA')
	AddTextEntry('JES21', 'Jauguar JES')
	AddTextEntry('22m5', 'BMW M5CS')
	AddTextEntry('gxone', 'Aguera R')
	AddTextEntry('ferrari812super', 'Ferrari 812 Super')
	AddTextEntry('g81hr', 'M3 Touring G81')
	AddTextEntry('fk8', 'Honda Civic')
	AddTextEntry('f8kspider', 'Audi Spider')
	AddTextEntry('rs7', 'Audi R7')
	AddTextEntry('rs7wide', 'Audi RS7Wide')
	AddTextEntry('rs615', 'Audi RS6')
	AddTextEntry('911gtrs', 'Porsche 911GTRS')
	AddTextEntry('m135iwb', 'BMW M135I')
	AddTextEntry('gtz34be', 'GT 34')
	AddTextEntry('mayb900', 'Brabus 900')
	AddTextEntry('mercec63s', 'AMG 63S')
	AddTextEntry('16charger', 'Dodge Charger')
	AddTextEntry('cayen19', 'Porsche Cayen')
	AddTextEntry('bentaygam', 'Bentlay')
	AddTextEntry('m4speedhunter', 'M4 Speed')
	AddTextEntry('g700brabusretuned', 'Brabus G700')
	AddTextEntry('G65', 'Mercedez G65')
	AddTextEntry('hellcatf9', 'Dodge Charger Hellcat')
	AddTextEntry('rmodskyline34', 'Skyline R34')
	AddTextEntry('AGERARS', 'Koenigsegg Agera')
	AddTextEntry('BEN17', 'Bentley Ben')
	AddTextEntry('q8hycade', 'Audi RSQ8')
	AddTextEntry('carsonswbc6', 'Chevrolet Corvette C6')
	AddTextEntry('rs5mans', 'Audi RS5')
	AddTextEntry('g900przemo6x6', 'Brabus G900')
	AddTextEntry('q8prior', 'Audi Q8')
	AddTextEntry('rmodmustang', 'Ford Mustang')
	AddTextEntry('evoss', 'Mitsubishi Evos')
	AddTextEntry('mteche39', 'BMW E39')
	AddTextEntry('hellcatlb', 'HELLLB')
	AddTextEntry('evo9', 'Mitsubishi Evo9')
	AddTextEntry('eleanor', 'Ford Mustang Eleanor')
	AddTextEntry('e92bb', 'BMW E92')
	AddTextEntry('polestar1', 'Polestar')
	AddTextEntry('evox', 'Mitsubishi Evo X')
	AddTextEntry('rx7veilside', 'Mazda RX7')
	AddTextEntry('mlnovitec', 'Masserati Levante')
	AddTextEntry('rmodm3e36', 'BMW E36')
	AddTextEntry('jcw', 'Mini CooperSport')
	AddTextEntry('na6', 'Mazda NA6')

--



	AddTextEntry('c63', 'Mercedes C63 AMG')
	AddTextEntry('cb500f', 'Honda CB500F 2018')
	AddTextEntry('cls53', 'Mercedes CLS53 AMG')
	AddTextEntry('dodgeEMS', 'Dodge EMS')
	AddTextEntry('fct', 'Ferrari Californiat 2017')
	AddTextEntry('macla', 'Mercedes Class A')
	AddTextEntry('mlbrabus', 'Mercedes Brabus')
	AddTextEntry('rs7r', 'Audi RS7-R ABT')
	AddTextEntry('divo', 'Bugatti Divo')
	AddTextEntry('tmax', 'Yamaha T-Max')
	AddTextEntry('urus2018', 'Lamborghini Urus 2018')
	AddTextEntry('ghispo2', 'maseratiPOLICE')
	AddTextEntry('rs318', 'Audi RS3')
	AddTextEntry('terzo', 'Lamborghini-Terzo')
	AddTextEntry('gtr', 'Nissan GTR')
	AddTextEntry('q820', 'Audi Q8')
	AddTextEntry('brabus700', 'Brabus X6 700')
	AddTextEntry('g770', 'Lumma G770')
	AddTextEntry('r820', 'Audi R820')
	AddTextEntry('rmodlfa', 'Lexus LFA')
	AddTextEntry('2f2frx7', '1994 Mazda RX-7')
	AddTextEntry('2f2fs2000', '2001 Honda S2000')
	AddTextEntry('350zdk', '2002 Nissan 350z DK')
	AddTextEntry('350zm', '2002 Nissan 350z Morimoto')
	AddTextEntry('fnfjetta', '1995 Volkswagen Jetta')
	AddTextEntry('fnfrx7dom', '1993 Mazda RX-7')
	AddTextEntry('gle53', 'AMG GLE 53')
	AddTextEntry('chargerf8', 'Charger F8')
	AddTextEntry('911turbos', '911turbos')
	AddTextEntry('AMGGTRR20', 'CoupÃ© AMG GTR 2020')
	AddTextEntry('rmodgt63', 'Mercedes-AMG GT63 S Coupe')
	AddTextEntry('r820', 'Audi R8')
	AddTextEntry('kart', 'kart')
	AddTextEntry('e63amg', 'Mercedes-Benz E 63 AMG')
	AddTextEntry('supervolito2', 'Super Volito 2')

	AddTextEntry('MERS63C', 'Mercedes S63 AMG')
	AddTextEntry('rmodrs6', 'Audi RS6')
	AddTextEntry('rmodrs6r', 'Audi RS6-R ABT')
	AddTextEntry('rmodjeep', 'Jeep 4x4')
	AddTextEntry('rmodbolide', '2020 Bugatti Bolide')
	AddTextEntry('zl1', 'Chevrolet Camaro ZL1')
	AddTextEntry('yzfsm', 'Yamaha 450 YZF')
	AddTextEntry('rmodmi8lb', 'BMW I8')
	AddTextEntry('twingo', 'Twingo')
	AddTextEntry('a45amg', 'Mercedes-Benz A45 AMG')
	AddTextEntry('lp610', 'Lamborghini Huracan')
	AddTextEntry('lp700', 'Lamborghini Aventador')
	AddTextEntry('S63C217', 'Mercedes-AMG S63')
	AddTextEntry('rs666', 'RS 666')
	AddTextEntry('rmodbiposto', 'Abarth 695 Biposto')
	AddTextEntry('golf75r', 'Golf 7 R')
	AddTextEntry('rmodf12tdf', 'Ferrari F12 TDF')
	AddTextEntry('rmodg65', 'Mercedes G-65 AMG')
	AddTextEntry('rmoddarki8', 'BMW EVO i8')
	AddTextEntry('s1000rr', 'BMW S1000RR')
	AddTextEntry('SubaruSTI7', 'Subaru STI 7')
	AddTextEntry('rmodc63amg', 'C63 AMG')
	AddTextEntry('bmxP2', 'Bmx')
	AddTextEntry('rmodsianr', 'Lamborghini Sian R')
	AddTextEntry('rmode63s', 'Mercedes-AMG E 63 S')
	AddTextEntry('rmodlp670', 'Lamborghini Murcielago')
	AddTextEntry('rmodlp770', 'Lamborghini Centenario')
	AddTextEntry('rmodx6', 'BMW X6')
	AddTextEntry('rmodsuprapandem', 'Toyota GR Supra Pandem RB')
	AddTextEntry('rmodz350pandem', 'Nissan 350Z RB')
	AddTextEntry('rmodbugatti', 'La Voiture Noire')
	AddTextEntry('rmodrs7', 'Audi RS7 Sportback')
	AddTextEntry('dodgeems', 'Dodge EMS')
	AddTextEntry('rmodf40', 'Ferrari F40')
	AddTextEntry('ksd', 'KTM Super Duke R')
	AddTextEntry('rmod240sx', 'Nissan 240SX')
	AddTextEntry('rmodbacalar', 'Bentley Mulliner Bacalar')
	AddTextEntry('rmodrover', 'Range Rover MANSORY')
	AddTextEntry('RS7C8WB', 'Audi RS7 2NCS Wide Body')
	AddTextEntry('rmodi8ks', 'BMW I8M Liberty Walk')
	AddTextEntry('rmodrs7', 'Audi RS7')
	AddTextEntry('pmansory', 'Porsche Panamera Mansory')
	AddTextEntry('mxv450sm', 'Aprilia MXV 450')
	AddTextEntry('pstmansory', 'Porsche Cayenne Mansory')
	AddTextEntry('rmodm4gts', 'BMW M4 GTS')
	AddTextEntry('mlmansory', 'Levante Mansory')
	AddTextEntry('rmodgtr50', 'Nissan GT-R50')
	AddTextEntry('bugatti', 'Bugatti Veyron')
	AddTextEntry('velociraptor', 'Hennessey Velociraptor 6x6')
	AddTextEntry('720s', 'McLaren 720S')
	AddTextEntry('rmodlego1', 'Lego Chiron')
	AddTextEntry('rmodlego2', 'Lego F40')
	AddTextEntry('rmodlego3', 'Lego Cooper')
	AddTextEntry('rmodlegoporsche', 'Lego Porsche')
	AddTextEntry('rmodlegosenna', 'Lego Senna')
	AddTextEntry('rmodm5e34', 'Bmw M5 E34')
	AddTextEntry('450crf', 'Honda CRF 450')
	AddTextEntry('golf7gti', 'Golf 7 GTI')
	AddTextEntry('teslapd', 'Tesla PRIOR')
	AddTextEntry('RAPTOR150', 'Ford Raptor 2017')
	AddTextEntry('2019gt3rs', 'Porsche 911 GT3 RS')
	AddTextEntry('2020exc', '2020 KTM EXC450')
	AddTextEntry('rmodcharger69', 'Dodge Charger 1969')
	AddTextEntry('rmodjesko', 'Koenigsegg Jesko')
	AddTextEntry('gladiator', 'Jeep Gladiator Rubicon')
	AddTextEntry('redeye', 'Dodge Challenger Redeye')
	AddTextEntry('w140gto', 'Mercedes-Benz AMG S600')
	AddTextEntry('19raptor', 'Ford 19 Raptor')
	AddTextEntry('rmodspeed', 'McLaren Speedtail')
	AddTextEntry('rmodp1gtr', 'McLaren P1 GTR')
	AddTextEntry('ARTURA22WB', 'McLaren Artura')
	AddTextEntry('GHOSTSWB', 'Rolls-Royce Ghost')
	AddTextEntry('GHOSTEWB1', 'Rolls-Royce Ghost')
	AddTextEntry('GHOSTSWB1', 'Rolls-Royce Ghost')
	AddTextEntry('GHOSTEWB', 'Rolls-Royce Ghost')
	AddTextEntry('RS6C8', 'Audi RS6 C8')
	AddTextEntry('r8spyder20', 'Audi R8 Spyder')
	AddTextEntry('g63topcar', 'G63 INFERNO')
	AddTextEntry('por718gt4', 'Porsche 718 Cayman GT4')
	AddTextEntry('roma20', '2020 Ferrari Roma')
	AddTextEntry('porto18', '2018 Ferrari Portofino')
	AddTextEntry('rs520', 'Audi RS5 Coupe')
	AddTextEntry('rs6rabt20', 'Audi RS6-R ABT')
	AddTextEntry('amgone', 'Mercedes AMG One')
	AddTextEntry('gle63', 'Mercedes-AMG GLE 63 S Coupe')
	AddTextEntry('gle63c', 'Lumma CLR G 800')
	AddTextEntry('gle53', 'Mercedes-AMG GLE 53')
	AddTextEntry('rmodporsche918', 'Porsche 918 Widebody')
	AddTextEntry('rmodsennagtr', 'McLaren Senna GTR')
	AddTextEntry('rmodm4', 'BMW M4')
	AddTextEntry('rmodr8c', 'Audi R8 Sypeder')
	AddTextEntry('rmodrs6police', 'Audi RS6 Police')
	AddTextEntry('s65amg', 'Mercedes-Benz S65 AMG')
	AddTextEntry('gls600', 'Mercedes-Maybach GLS 600')
	AddTextEntry('gls20', 'Mercedes-AMG GLS 63 2020')
	AddTextEntry('gls63_de_dmz', 'Mercedes-AMG GLS 63 Renforce')
	AddTextEntry('g632019', 'Mercedes-AMG G 63 2019')
	AddTextEntry('amggt320', 'Mercedes-AMG GT 320')
	AddTextEntry('amggtbs', 'Mercedes-AMG GT Black Series')
	AddTextEntry('amggtr', 'Mercedes-AMG GT R')

	--- ARME PERM

	AddTextEntry("WEAPON_A15RC", "A15RC PERM")
	AddTextEntry("WEAPON_NEVA", "Neva PERM")
	AddTextEntry("WEAPON_IAR", "Iar PERM")
	AddTextEntry("WEAPON_M133", "M133 PERM")
	AddTextEntry("WEAPON_JRBAK", "Jrbak PERM")
	AddTextEntry("WEAPON_FAMASU1", "Famasus PERM")
	AddTextEntry("WEAPON_UZI", "Uzi PERM")
	AddTextEntry("WEAPON_UMP45", "Ump45 PERM")

	AddTextEntry("WEAPON_GLOCK17", "Glock17 PERM")



	AddTextEntry("WEAPON_GYS", "GYS PERM")
	AddTextEntry("WEAPON_M416P", "M416P PERM")
	AddTextEntry("WEAPON_ENERGYKNIFE", "ENERGYKNIFE PERM")
	AddTextEntry("WEAPON_KARAMBIT", "KARAMBIT PERM")

	-- NON PERM
AddTextEntry('WEAPON_OWSHOTGUN', 'Owshotgun NON-PERM')
AddTextEntry('WEAPON_H2SMG', 'H2smg NON-PERM')
AddTextEntry('WEAPON_CZ75', 'CZ75 NON-PERM')
AddTextEntry('WEAPON_PL14', 'PL14 NON-PERM')
AddTextEntry('WEAPON_ACWR', 'Acwr NON-PERM')
AddTextEntry('WEAPON_AK47', 'Ak47 NON-PERM')
AddTextEntry('WEAPON_ANARCHY', 'Anarchy NON-PERM')
AddTextEntry('WEAPON_G3_2', 'G32 NON-PERM')
AddTextEntry('WEAPON_HOWA_2', 'Howa2 NON-PERM')
AddTextEntry('WEAPON_LR300', 'Lr300 NON-PERM')
AddTextEntry('WEAPON_SCARSC', 'Scarsc NON-PERM')
AddTextEntry('WEAPON_FN502', 'Fn502 NON-PERM')
AddTextEntry('WEAPON_KNR', 'KNR NON-PERM')

--
	
	AddTextEntry('amggtsprior', 'Mercedes-AMG GT S Prior-Design')
	AddTextEntry('brabus500', 'BRABUS Mercedes G500 4x4')
	AddTextEntry('BRABUS700', 'Brabus 700 6x6')
	AddTextEntry('brabuse700', 'Brabus 700')
	AddTextEntry('cbr1000rrr', 'Honda CBR1000RR-R')
	AddTextEntry('g650', 'Mercedes-Maybach G 650')
	AddTextEntry('gt63', 'Mercedes GT63')

	AddTextEntry('rmodsupra', 'Toyota Supra')
	AddTextEntry('911gt3r', 'Porsche 911 GT3 R')
	AddTextEntry('800pro', 'JetSki')
	AddTextEntry('rs7c821', '2021 Audi RS7 Sportback')
	AddTextEntry('polmav2', 'Police Maverick')
	AddTextEntry('mh65c', 'HH-65 Dolphin')
end)