---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iTexZ.
--- DateTime: 05/11/2020 02:17
---

local TextPanels = {
    Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 0.25, Width = 431, Height = 42 },
}

---@type Panel
function RageUIv1.RenderSprite(Dictionary, Texture)
    local CurrentMenu = RageUIv1.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, CurrentMenu.Y + TextPanels.Background.Y + CurrentMenu.SubtitleHeight + RageUIv1.ItemOffset + (RageUIv1.StatisticPanelCount * 42), TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 200, 0, 255, 255, 255, 255);
            RageUIv1.StatisticPanelCount = RageUIv1.StatisticPanelCount + 1
        end
    end
end


---@type Panel
function RageUIv1.RenderWeapons(Dictionary, Texture)
    local CurrentMenu = RageUIv1.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 334.50, TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 200, 0, 255, 255, 255, 255);
            RageUIv1.StatisticPanelCount = RageUIv1.StatisticPanelCount + 1
        end
    end
end
---@type Panel
function RageUIv1.CaissePreviewOpen(Dictionary, Texture)
    local CurrentMenu = RageUIv1.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, CurrentMenu.Y + TextPanels.Background.Y + CurrentMenu.SubtitleHeight + RageUIv1.ItemOffset + (RageUIv1.StatisticPanelCount * 42), TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 200, 0, 255, 255, 255, 255);
            RageUIv1.StatisticPanelCount = RageUIv1.StatisticPanelCount + 1
        end
    end
end
---@type Panel
function RageUIv1.RenderCaisse(Dictionary, Texture)
    local CurrentMenu = RageUIv1.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 380.25, TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 200, 0, 255, 255, 255, 255);
            RageUIv1.StatisticPanelCount = RageUIv1.StatisticPanelCount + 1
        end
    end
end

---@type Panel
function RageUIv1.RenderCaissePreview(Dictionary, Texture)
    local CurrentMenu = RageUIv1.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 560.25, TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 200, 0, 255, 255, 255, 255);
            RageUIv1.StatisticPanelCount = RageUIv1.StatisticPanelCount + 1
        end
    end
end

---@type Panel
function RageUIv1.RenderJournalier(Dictionary, Texture)
    local CurrentMenu = RageUIv1.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 400.25, TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 200, 0, 255, 255, 255, 255);
            RageUIv1.StatisticPanelCount = RageUIv1.StatisticPanelCount + 1
        end
    end
end

local BoxSettings = {
    itemPerLine = 4,
    width = 215,
    height = 120,
    Kay = 5
}

function RageUIv1.RenderBox(Items)
    local lastLine = 0;
    for k, v in pairs(VisualitionCaisse[Items]) do
        local x = 525 + (((k -1) - (BoxSettings.itemPerLine * lastLine)) * (BoxSettings.width + BoxSettings.Kay))
        local y = (lastLine * (BoxSettings.height + BoxSettings.Kay))
        RenderSprite("caissemystere", v.model, x, y, BoxSettings.width, BoxSettings.height, 0, 255, 255, 255, 255)
        if math.tointeger(k / BoxSettings.itemPerLine) ~= nil then
            lastLine = math.tointeger(k / BoxSettings.itemPerLine)
        end
    end
end