--[[
  This file is part of Koy RolePlay.
  Copyright (c) Koy RolePlay - All Rights Reserved
  Unauthorized using, copying, modifying and/or distributing of this file,
  via any medium is strictly prohibited. This code is confidential.
--]]

PoliceConfigAAA = {

  amende = {
      ["amende "] = {
          {label = 'Usage abusif du klaxon', price = 150},
          {label = 'Franchir une ligne continue', price = 100},
          {label = 'Circulation à contresens', price = 200},
          {label = 'Demi-tour non autorisé', price = 150},
          {label = 'Conduite hors route / hors piste', price = 200},
          {label = 'Stationnement gênant / interdit', price = 100},
          {label = 'Non-respect d\'un stop', price = 80},
          {label = 'Véhicule non en état', price = 150},
          {label = 'Conduite sans permis', price = 2500},
          {label = 'Délit de fuite', price = 3000},
          {label = 'Excès de vitesse < 5 kmh', price = 100},
          {label = 'Excès de vitesse 5-15 kmh', price = 200},
          {label = 'Excès de vitesse 15-30 kmh', price = 300},
          {label = 'Excès de vitesse > 30 kmh', price = 400},
          {label = 'Dégradation de bien publique', price = 200},
          {label = 'Trouble à l\'ordre publique', price = 2000},
          {label = 'Entrave opération de police', price = 20000},
          {label = 'Insulte envers / entre civils', price = 500},
          {label = 'Menace et / ou intimidation envers civil', price = 2000},
          {label = 'Menace et ou intimidation envers un représentant de état', price = 55000},
          {label = 'Manifestation illégale', price = 500},
          {label = ' corruption', price = 30000},
          {label = 'Arme blanche sortie en publique', price = 2000},
          {label = 'Arme létale sortie en publique', price = 4000},
          {label = 'Port d\'arme illégal', price = 35000},
          {label = 'Vol de voiture', price = 2000},
          {label = 'Vente de produit illégaux', price =1000},
          {label = 'Fabrication de produit illégaux', price = 3000},
          {label = 'Possession de Produit illégaux 10 +', price = 6000},
          {label = 'Possession de Produit illégaux - 10', price = 4000},
          {label = 'Prise d\'ôtage civil', price = 65000},
          {label = 'Prise d\'ôtage agent de l\'état', price = 100000},
          {label = 'Braquage supérette', price = 20000},
          {label = 'Braquage de banque', price = 300000},
          {label = 'Tir sur civil', price = 60000},
          {label = 'Tir sur agent de l\'état', price = 120000},
          {label = 'Tentative d\'homicide sur civil', price = 40000},
          {label = 'Tentative d\'homicide sur agent de l\'état', price = 60000},
          {label = 'Meurtre sur civil', price = 80000},
          {label = 'Meurte sur Fonctionnaire', price = 200000},
          {label = 'exhibition en publique', price = 5000},
          {label = 'occupation illegal de eKay publique', price = 2000},
          {label = 'tentative de kidnapping séquestration', price = 30000},
          {label = 'kidnapping séquestration', price = 50000},
          {label = 'complicité de tir', price = 6000},
          {label = 'complicité de meurtre', price = 30000},
          {label = 'multiple kidnapping séquestration', price = 100000},
          {label = 'tentative évasion', price = 25000},
          {label = 'kidnapping séquestration', price = 20000},
          {label = 'évasion', price = 7000},
          {label = 'participation à une fusillade', price = 5000},
          {label = 'intrusion dans un PDP', price = 10000},
          {label = 'abus de pouvoir', price = 9000},
          {label = 'vol à main armée', price = 5000},
          {label = 'vente illegal', price = 5000},
          {label = 'agression sur civil', price = 6000},
          {label = 'agression sur représentant de état', price = 8000},
          {label = 'port équipement illegal', price = 20000},
          {label = 'blanchiment argent', price = 12000},
          {label = 'possession argent sale', price = 10000},
          {label = 'coup et blessure sur civil', price = 4000},
          {label = 'mise en danger de la vie autruit', price = 6000},
          {label = 'outrage envers un représentant de état', price = 3000},
          {label = 'outrage envers un magistrat', price = 5000},
          {label = 'refu optempérer', price = 4500},
          {label = 'conduite véhicule volé', price = 3000},
          {label = 'dissimulation du visage sur la voie publique', price = 2000},
          {label = 'entrave a la circulation', price = 1500},
      }
    },
  }
  